name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build, publish image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt-hotspot
          java-version: '17'
          cache: maven

      - name: Compile
        run: mvn clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push
        uses: docker/build-push-action@v6
        with:
          file: "./src/main/docker/Dockerfile.jvm"
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Commit message: ${{ github.event.head_commit.message }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
