name: Publish Native Docker image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish_native:
    name: Build and publish native Quarkus executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt-hotspot
          java-version: '17'
          cache: maven

      - name: Compile
        run: mvn clean package -DskipTests -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push
        uses: docker/build-push-action@v6
        with:
          file: "./src/main/docker/Dockerfile.native-distroless"
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}-native
            org.opencontainers.image.description=Commit message: ${{ github.event.head_commit.message }}
          tags: |
            ghcr.io/${{ github.repository }}-native:latest
            ghcr.io/${{ github.repository }}-native:${{ github.sha }}
